### ISSUE TITLE
Lets connect for some collab

### ISSUE THREAD

**Issue by debarko** [isahanabhat/nse_xbrl#1]
Hey,

I am working on some project where I need to parse the XBLR INS AS format. I used your script and it worked fine for me. I wanna know understand this slightly better so that I understand the pitfalls slightly better as to where it won't work and all. Lets connect. Can you reach out on [Linkedin](https://www.linkedin.com/in/debarkode/). Can't find any contact info hence just raising an issue here.

**Comment by isahanabhat** [comment]
Thank you for using my code and the feedback provided.
I can be reached at https://www.linkedin.com/in/isahanabhat/
